pipeline:
  inputs:
    - name: tail
      path: /log-root/business-pcx/dev-business-pcx/PCXWebService/PCXWebService.log
      read_from_head: true

  outputs:
    - name: loki
      host: loki
      port:   3100
      labels: agent=fluent-bit
      match: '*'