parsers:
  - name: ipex_parser
    format: regex
    regex: '/^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}) -- (?<logLevel>[^--]*) -- (?<application>[^--]*) -- (?<log>.*)/'
    # regex: '/^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) -- (?<logLevel>[^--]*) -- (?<application>[^--]*) -- (?<log>.*)/'
    time_key: time
    # time_format: '%Y-%m-%d %H:%M:%S'
    time_format: '%Y-%m-%d %H:%M:%S,%L'

pipeline:
  inputs:
    - name: tail
      path: /log-root/business-pcx/dev-business-pcx/PCXWebService/PCXWebService.log
      # read_from_head: true
    - name: tail
      path: /log-root2/PCXWebService/PCXWebService.log
      parser: ipex_parser
      # read_from_head: true
    
    - name: tail
      path: /log-root2/MyApp.log
      parser: ipex_parser
      # read_from_head: true


  outputs:
    - name: loki
      host: loki
      port:   3100
      labels: agent=fluent-bit
      match: '*'
      label_keys: $logLevel, $log, $application

    - name: stdout
      match: '*'